openapi: 3.1.0
info:
  title: TD-5 Specification
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ingredients:
    get:
      summary: get all ingredients
      responses:
        '200':
          description: list of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

components:
  schemas:
    Ingredient:
      type: object
      required:
        - id
        - name
        - category
        - price
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          $ref: '#/components/schemas/CategoryEnum'
        price:
          type: number
          format: float

    CategoryEnum:
      type: string
      enum:
        - VEGETABLE
        - ANIMAL
        - MARINE
        - DAIRY
        - OTHER