openapi: 3.1.0
info:
  title: TD-5 Specification
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ingredients:
    get:
      tags:
        - Ingredients
      summary: get all ingredients
      responses:
        '200':
          description: list of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
                  
  /ingredients/{id}:
    get:
      tags:
        - Ingredients
      summary: get ingredient by id
      parameters:
        - $ref: '#/components/parameters/IdParameter'
      responses:
        '200':
          description: ingredient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'

        '404':
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                example: "Ingredient.id=8 is not found"

  /ingredients/{id}/stock:
    get:
      tags:
        - Ingredients
      summary: get stock value of an ingredient at a given time
      parameters:
        - $ref: '#/components/parameters/IdParameter'

        - name: at
          in: query
          required: false
          schema:
            type: string
            format: date-time

        - name: unit
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/UnitType'  

      responses:
        '200':
          description: stock value of ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockValue'
        
        '400':
          description: at or unit is undefined
          content:
            text/plain:
              schema:
                type: string
                example: 'Either mandatory query parameter `at` or `unit` is not provided.'
        
        '404': 
          description: ingredient not found
          content:
            text/plain:
              schema:
                type: string
                example: "Ingredient.id=8 is not found"
  
  /dishes:
    get:
      tags:
        - Dishes
      summary: get all dishes
      responses:
        '200':
          description: dishes found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
  
  /dishes/{id}/ingredients:
    put:
      tags:
        - Dishes
      summary: update ingredients of a dish
      parameters:
        - $ref: '#/components/parameters/IdParameter'

      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'

      responses:
        '200':
          description: ingredients updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'

        '400':
          description: missing request body
          content:
            text/plain:
              schema:
                type: string
                example: "Request body is required"

        '404':
          description: dish not found
          content:
            text/plain:
              schema:
                type: string
                example: "Dish.id=8 is not found"
        

        



components:
  parameters:
    IdParameter:
      name: id
      in: path
      required: true
      schema:
        type: integer
  schemas:
    Ingredient:
      type: object
      required:
        - id
        - name
        - category
        - price
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          $ref: '#/components/schemas/CategoryEnum'
        price:
          type: number
          format: float

    CategoryEnum:
      type: string
      enum:
        - VEGETABLE
        - ANIMAL
        - MARINE
        - DAIRY
        - OTHER
    
    UnitType:
      type: string
      enum:
        - PCS
        - KG
        - L
    
    StockValue:
      type: object
      required:
        - quantity
        - unit
      properties:
        quantity:
          type: number
          format: float
        unit:
          $ref: '#/components/schemas/UnitType'

    Dish:
      type: object
      required:
        - id
        - name
        - price
        - ingredients
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        ingredients: 
          type: array
          items: 
            $ref: '#/components/schemas/Ingredient'
        
